# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: 0.1.{build}

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\PSScriptAnalyzer -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\Pester -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\PSFramework -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\dbatools -> appveyor.yml

shallow_clone: true

environment:
  environment: development
  version: 0.1.$(appveyor_build_number)

matrix:
  fast_finish: true

build_script:
# grab appveyor lab files and needed requirements for tests in CI
- ps: .\tests\appveyor_preparation.ps1

test_script:
# Test with PowerShell and Pester
- ps: .\tests\pester.ps1